#ifndef SW0_GPIO_CONTROLLER
#ifdef SW0_GPIO_NAME
#define SW0_GPIO_CONTROLLER SW0_GPIO_NAME
#else
#error SW0_GPIO_NAME or SW0_GPIO_CONTROLLER needs to be set in board.h
#endif
#endif
#define BUTTON_CONTROLLER SW0_GPIO_CONTROLLER

#ifdef SW0_GPIO_PIN
#define BUTTON SW0_GPIO_PIN
#define ENCODER_CHANNEL_A SW1_GPIO_PIN
#define ENCODER_CHANNEL_B SW2_GPIO_PIN
#else
#error SW0_GPIO_PIN needs to be set in board.h
#endif

#ifdef SW0_GPIO_FLAGS
#define EDGE (SW0_GPIO_FLAGS | GPIO_INT_EDGE)
#else
#define EDGE (GPIO_INT_EDGE | GPIO_INT_ACTIVE_LOW)
#endif

#ifndef SW0_GPIO_FLAGS
#ifdef SW0_GPIO_PIN_PUD
#define SW0_GPIO_FLAGS SW0_GPIO_PIN_PUD
#else
#define SW0_GPIO_FLAGS 0
#endif
#endif
#define PULL_UP SW0_GPIO_FLAGS

#define STANDARD_BUTTON GPIO_DIR_IN | GPIO_INT | PULL_UP | EDGE

#define SLEEP_TIME 500

#define MAX_PWM_PERIOD (USEC_PER_SEC / 50)
#define MIN_PWM_PERIOD 0

#if defined(CONFIG_PWM_NRF5_SW)
#define PWM_DRIVER CONFIG_PWM_NRF5_SW_0_DEV_NAME
#else
#define PWM_DRIVER CONFIG_PWM_0_NAME
#endif /* CONFIG_PWM_NRF5_SW */
#define PWM_CHANNEL0 LED0_GPIO_PIN
#define PWM_CHANNEL1 LED1_GPIO_PIN
#define PWM_CHANNEL2 LED2_GPIO_PIN
#define PWM_CHANNEL3 LED3_GPIO_PIN
#define PWM_CHANNEL4 LED4_GPIO_PIN

#define MAX_BRIGHTNESS 65535.0
#define MIN_BRIGHTNESS 0.0
#define NUMBER_OF_LEDS 5
#define LED_BRIGHTNESS_PART (100 / NUMBER_OF_LEDS)